version: "3"
services:
  kofy-back:
    container_name: kofy-back
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=diego_gtz_t@hotmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - kofy-back

volumes:
  nginx_secrets: